name: Compile Examples ESP32
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32
          #- esp32:esp32:esp32c2
          - esp32:esp32:esp32c3
          - esp32:esp32:esp32s3

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - examples/Central/Scan
